version: '3.9'

services:
  backend:
    container_name: backend_go
    image: backend_go
    build: .
    environment:
      DATABASE_URL: "host=postgres user=postgres password=25101989 dbname=postgres port=5432 sslmode=disable "
    ports:
      - "8080:8080"


  database:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: "25101989"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgAdmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "andrew.nevsky@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "25101989"
    ports :
      - 5050:80


volumes:
  pgdata: {}




